config/routes.rb
Rails.application.routes.draw do
resources :user_sessions
resources :users

get 'login' => 'user_sessions#new', :as => :login
post 'logout' => 'user_sessions#destroy', :as => :logout

  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
  resources :cards
  post 'sub', to: 'home#sub'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class RecordValidator < ActiveModel::Validator
  def validate(record)
    if record.original_text.strip.upcase === record.translated_text.strip.upcase
      record.errors[:base] << "This person is evil"
    end
  end
end

class Card < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :user
  before_create :normalize_card_review_date
  validates_with RecordValidator
  scope :review_date, -> { where('review_date <= ?', Time.now).order('RANDOM()') }
  def check_translation(user_input) 
    translated_text === user_input 
  end

  def update_review_date
    normalize_card_review_date && save
  end 

  def normalize_card_review_date
    self.review_date = Time.now + 3.days
  end

end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!


  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  validates :email, uniqueness: true
  has_many :cards
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_login
  protect_from_forgery with: :exception
  private
def not_authenticated
  redirect_to login_path, alert: "Please login first"
end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
    def index
      @cards = current_user.cards.all
    end
 
    def new
      @card = Card.new
    end
    def edit
    @card = Card.find(params[:id])
    end
    def update
    @card = Card.find(params[:id])
    if @card.update(card_params)
    redirect_to(@card)
    else
    render "edit"
    end
    end
    def create
    @card = current_user.cards.new(card_params)
  
    if @card.save
    redirect_to @card, notice: 'The card was created successfully.'
    else
    flash[:error] = 'There was an error creating the card.'
    render :new
    end    
    end
    def destroy
    @card = Card.find(params[:id])
    @card.destroy

    respond_to do |format|
    format.html { redirect_to(cards_url) }
    format.xml  { head :ok }
    end
    end
    def show
    @card = Card.find(params[:id])
    end
    private
    def card_params
    params.require(:card).permit(:original_text, :translated_text,:review_date,:user_id,:image)
    end
    end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @card = Card.review_date.first
  end

  def sub
    @card = Card.find(params[:id])
    if @card.check_translation(params[:user_translation])
      @card.update_review_date
      flash.now[:notice] = 'Правильно'
    else 
      flash.now[:error] = 'Не правильно'
    end
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, except: [:destroy]
  def new
    @user = User.new
  end

  def create
    if @user = login(params[:email], params[:password])
      redirect_back_or_to(:users, notice: 'Login successful')
    else
      flash.now[:alert] = 'Login failed'
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_to(:users, notice: 'Logged out!')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 skip_before_action :require_login, only: [:index, :new, :create]
  
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save 
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cards/_form.html.erb
<%= simple_form_for @card do |f| %>
  <%= f.input:image,as: :file, label: 'Image' ,required: false %>
  <%= f.input :original_text, label: 'Original Text' ,required: false %>
  <%= f.input :translated_text, label: 'Translated Text' , required: false %>
  <%= f.button :submit %>
<%= link_to 'Back', cards_path %>
<% end %>

app/views/cards/edit.html.erb
<%= render "form" %>

app/views/cards/index.html.erb
     <ul class="list-group">
<% @cards.each do |card| %>

  <li class="list-group-item"><%= card.original_text %>
<%= link_to  edit_card_path(card) do %>
     <span class="glyphicon glyphicon-pencil" aria-hidden="true"> </span>
<% end %>
<%= link_to  card_path(card) , method: :delete do %>
     <span class="glyphicon glyphicon-trash" aria-hidden="true"> </span>
<% end %>
  
  </li>
<% end %>
    </ul>

app/views/cards/new.html.erb
<h1>New Text</h1>
<%= render "form" %>

app/views/cards/show.html.erb
<%= @card.original_text %>
<%= @card.review_date %>
     <%= image_tag(@card.image_url) if @card.image? %>

app/views/home/index.html.erb
<section>
  <p style="font-size: 22px;">
    Первый в мире удобный менеджер флеш-карточек. Именно так.
  </p>
   <% if @card %>
     <%= @card.original_text %>
     <%= image_tag(@card.image_url) if @card.image? %>
     <%= form_tag('/sub', method: :post)  do %>
      <%= text_field_tag(:user_translation) %>
      <%= hidden_field_tag 'id', @card.id %>
      <%= submit_tag 'Check' %>
     <% end %>
  <% end %>
</section>

app/views/home/sub.html.erb
<% flash.each do |key, message| %>
  <p class="<%= key %>"><%= message %></p>
<% end %>
<%= @card.review_date %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Флэшкарточкер</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<body>
  <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Флэшкарточкер</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
     
      <ul class="nav navbar-nav navbar-right">
     
            <% if current_user %>
      <%= link_to "Edit Profile", edit_user_path(current_user.id) %>
      <%= link_to "Logout", :logout, method: :post %>
      <%= link_to "All Cards", cards_path %>
      <%= link_to "Add Card", new_card_path %>
    <% else %>
      <%= link_to "Register", new_user_path %> |
      <%= link_to "Login", :login %>
    <% end %>
      </ul>
        <div>
    <p id="notice"><%= flash[:notice] %></p>
    <p id="alert"><%= flash[:alert] %></p>
  </div>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
  </nav>
  <% flash.each do |key, message| %>
  <div id="flash-<%= key %>" class="flash-<%= key %>">
    <%= message %>
  </div>
<% end %>
  <section id="container">
              <%= yield %>
  </section>
</body>
</html>

app/views/user_sessions/_form.html.erb
<%= form_tag user_sessions_path, :method => :post  do %>
  <div class="field">
    <%= label_tag :email %><br />
    <%= text_field_tag :email %>
  </div>
  <div class="field">
    <%= label_tag :password %><br />
    <%= password_field_tag :password %>
  </div>
  <div class="actions">
    <%= submit_tag "Login" %>
  </div>
<% end %>

app/views/user_sessions/create.html.erb
<h1>UserSessions#create</h1>
<p>Find me in app/views/user_sessions/create.html.erb</p>

app/views/user_sessions/destroy.html.erb
<h1>UserSessions#destroy</h1>
<p>Find me in app/views/user_sessions/destroy.html.erb</p>

app/views/user_sessions/new.html.erb
<h1>Login</h1>

<%= render 'form' %>

<%= link_to 'Back', user_sessions_path %>

app/views/users/_form.html.erb
<%= simple_form_for(:user) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :email %>
<div class="field">
   <%= f.label :password %><br />
   <%= f.password_field :password %>
</div>
<div class="field">
   <%= f.label :password_confirmation %><br />
   <%= f.password_field :password_confirmation %>
</div>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Crypted password</th>
      <th>Salt</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.crypted_password %></td>
        <td><%= user.salt %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>Login</h1>

<%= render 'form' %>

<%= link_to 'Back', user_sessions_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Crypted password:</strong>
  <%= @user.crypted_password %>
</p>

<p>
  <strong>Salt:</strong>
  <%= @user.salt %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>